# Generated by Django 5.0.6 on 2024-06-13 17:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.CharField(max_length=50)),
                ('Desription', models.TextField()),
                ('Priority', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], max_length=1)),
                ('DateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
    ]
