# Generated by Django 5.0.6 on 2024-06-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Desription',
            new_name='Description',
        ),
    ]
